---
title: "Greenspace_Data"
author: "Veronica Strempfer"
date: "2026-02-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# identify unique cases of number of parks and acreage per city
library(readxl)
library(dplyr)

greenspace <- read_excel("Countywide_Parks_and_Open_Space.xlsx", sheet=1)
greenspace <- greenspace %>%
  group_by(CITY) %>%
  mutate(
    parks_in_city = n(),
    avg_acres_in_city = mean(GIS_ACRES, na.rm =TRUE)
  ) %>%
  ungroup()
greenspace

```

```{r}
sum(is.na(greenspace$CENTER_LAT))
sum(is.na(greenspace$CENTER_LON))
greenspace[is.na(greenspace$CENTER_LAT) | is.na(greenspace$CENTER_LON), ]

greenspace_clean <- greenspace %>%
  filter(!is.na(CENTER_LAT) & !is.na(CENTER_LON))
```



```{r}
# THIS IS THE DATA
library(sf)
library(tigris)

greenspace_clean <- greenspace %>%
  filter(!is.na(CENTER_LAT) & !is.na(CENTER_LON))

greenspace_sf <- st_as_sf(greenspace_clean, coords = c("CENTER_LON", "CENTER_LAT"),
                          crs = 4326)
ca_counties <- counties(state = "CA", cb=TRUE)
la_county <- ca_counties[ca_counties$NAME == "Los Angeles", ]

la_county <- st_transform(la_county, crs = st_crs(greenspace_sf))
greenspace_la <- st_filter(greenspace_sf, la_county)
greenspace_la <- st_drop_geometry(greenspace_la)

greenspace_access <- greenspace_la %>%
  filter(ACCESS_TYP == "Open Access")
greenspace_access

nrow(greenspace_clean)
nrow(greenspace_la) 
# 29 parks were outside LA county
```


```{r}
zip_check <- greenspace %>%
  group_by(ZIP) %>%
  summarise(calc_avg = mean(GIS_ACRES, na.rm = TRUE))

check <- greenspace %>%
  distinct() %>%
  left_join(zip_check, by = "ZIP") %>%
  mutate(match = round(avg_acres_in_zip, 5) == round(calc_avg, 5))
check %>% filter(match == FALSE)
```





